Create Hardware.cs
grigvardanyan/OS pull request #1
Opened 2017-03-31 17:37 UTC by Gor32

2017-03-31 17:37 UTC, Gor32 commented
dcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhgdcbgfhhhhg

2017-04-01 18:26 UTC, vmartirosyanHS requested changes

2017-04-01 18:26 UTC, vmartirosyanHS commented on Hardware.cs
> +            @"c:\Users\Home\documents\visual studio 2015\Projects\OS\Hardware\HDD.txt";
Use relative path.

2017-04-01 20:30 UTC, Gor32 commented on Hardware.cs
> +            @"c:\Users\Home\documents\visual studio 2015\Projects\OS\Hardware\HDD.txt";
ok 
Directory.GetCurrentDirectory()+"\\HDD.txt";   is true ?

2017-04-02 05:59 UTC, vmartirosyanHS commented on Hardware.cs
> +            @"c:\Users\Home\documents\visual studio 2015\Projects\OS\Hardware\HDD.txt";
Try yourself and put in working code.

2026-04-07 16:39 UTC, closed without merging